#!/bin/sh


all: 	
	@echo "hello"
//echo 'Building target: $@'
#Jinux.exe

#Jinux.exe: 
#	@echo 'Building target: $@'
#	@echo 'Invoking: MinGW C Linker'
#	gcc -T C:\\Users\\JunGeGe\\Documents\\GitHub\\Embedded-OS\\Jinux\\JunGe_i386pe.x  -o "Jinux.exe" $(OBJS) $(USER_OBJS) $(LIBS)
#	@echo 'Finished building target: $@'
#	@echo ' '
	
clean:
	make -C $(MyTOPDIR)/Library/Lib_base clean


.PHONY: all
run:
	bin/daemon 